# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdce68b226d2e06ab138dcaa270d236c4e762e1f8a013012aa83e0c8c55657fbee1e2b2f3b06ab0392554ec67e40cc4bdabb9bfcda61c895eae298244ff808a5

test:
  secret_key_base: 9720c5d029d0a5794908fa7cc17b2290489af4478c693dd17915cafd032c00d5c49437cd516a105cc7cb5b880b0374df6ce418e0a748038c5fdcb2dc3600a636

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
